spring:
  application:
    name: heima-ai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-ai?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:7b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model: qwen3.5-omni-plus
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024



logging:
  level:
    org.springframework.ai: DEBUG
    com.spring.springai: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
